### ISSUE TITLE
SQLALCHEMY_ECHO bug KEY error 

### ISSUE THREAD

**Issue by baotran2207** [pallets/flask-sqlalchemy#945] opened 2021-03-30 07:27 UTC
Even my `SQLALCHEMY_ECHO=False` , i face this issue whenever i have tried to upgrade both python and flask_sqlalchemy , sqlalchemy 
```File "/home/student/.pyenv/versions/3.9.1/envs/app-py-3.9.1/lib/python3.9/site-packages/sqlalchemy/log.py", line 96, in __init__
Mar 30 06:25:46 myhost app [20986]: if self._echo_map[echo] <= logging.INFO and not self.logger.handlers:
Mar 30 06:25:46 myhost app [20986]:       KeyError: 'False'
```

Versions:
 - python 3.9.1
 - Flask==1.1.2
 - Flask-SQLAlchemy==2.5.1
 - SQLAlchemy==1.3.23 
 - mysqlclient==2.0.3 
 - pymssql==2.1.5
 - My database : mariadb  10.4 

I have tried below `URI` but no luck :

`SQLALCHEMY_DATABASE_URI = 'mysql://username:password@127.0.0.1:3306/db'`
`SQLALCHEMY_DATABASE_URI = 'mysql+pymysql://username:password@127.0.0.1:3306/db'`
`SQLALCHEMY_DATABASE_URI = 'mysql+mysqldb://username:password@127.0.0.1:3306/db'`

So the question is ,what value is good for  `SQLALCHEMY_ECHO` ?

Ref:
 - https://github.com/pallets/flask-sqlalchemy/issues/724

**Comment by davidism** [comment] 2021-03-30 19:41
As with #724, closing since a minimal reproducible example was not provided. The following example works without error:

```python
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__)
app.config["SQLALCHEMY_DATABASE_URI"] = "sqlite:///:memory:"
app.config["SQLALCHEMY_ECHO"] = True

db = SQLAlchemy()

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)

with app.app_context():
    db.create_all()
    db.session.add(User())
    db.session.commit()
    print(db.session.query(User).all())
```

**Closed by davidism** 2021-03-30 19:41 UTC
