### ISSUE TITLE
Error on `db.create_all` with latest SQLAlchemy

### ISSUE THREAD

**Issue by dsbowen** [pallets/flask-sqlalchemy#925] opened 2021-03-15 19:27 UTC
Environment: python=3.9, sqlalchemy=1.4.0, flask-sqlalchemy=2.4.4

```python
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__)
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///test.db'
db = SQAlchemy(app)
db.create_all()
```

Output:

```
...
File "flask_sqlalchemy/__init__.py", line 914, in apply_driver_hacks
sa_url.database = os.path.join(app.root_path, sa_url.database)
AttributeError: can't set attribute
```

The error doesn't occur with SQLAlchemy=1.3.23

**Comment by ThiefMaster** [comment] 2021-03-15 19:28
Kind of a duplicate of #910. Pin `sqlalchemy<1.4` for now.

**Closed by ThiefMaster** 2021-03-15 19:28 UTC
