### ISSUE TITLE
quickstart documentation does not work

### ISSUE THREAD

**Issue by SlavaTimbaliuc** [pallets/flask-sqlalchemy#927] opened 2021-03-16 02:59 UTC
Using the quickstart documentation, getting AttributeError

Creating a file named app.py with the contents of the file from https://flask-sqlalchemy.palletsprojects.com/en/2.x/quickstart. 

```
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__)
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:////tmp/test.db'
db = SQLAlchemy(app)


class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)

    def __repr__(self):
        return '<User %r>' % self.username
```

Then, run `python`, and then in the interpreter,

```
from app import db
db.create_all()
```

I get 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/veaceslavtimbaliuc/.pyenv/versions/3.8.1/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 1039, in create_all
    self._execute_for_all_tables(app, bind, 'create_all')
  File "/Users/veaceslavtimbaliuc/.pyenv/versions/3.8.1/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 1031, in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), **extra)
  File "/Users/veaceslavtimbaliuc/.pyenv/versions/3.8.1/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 962, in get_engine
    return connector.get_engine()
  File "/Users/veaceslavtimbaliuc/.pyenv/versions/3.8.1/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 555, in get_engine
    options = self.get_options(sa_url, echo)
  File "/Users/veaceslavtimbaliuc/.pyenv/versions/3.8.1/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 570, in get_options
    self._sa.apply_driver_hacks(self._app, sa_url, options)
  File "/Users/veaceslavtimbaliuc/.pyenv/versions/3.8.1/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 914, in apply_driver_hacks
    sa_url.database = os.path.join(app.root_path, sa_url.database)
AttributeError: can't set attribute
```

Environment:

- Python version: 3.8.1
- Flask-SQLAlchemy version: 2.4.4
- SQLAlchemy version: 1.4

**Comment by davidism** [comment] 2021-03-16 04:06
Duplicate of #910

**Closed by davidism** 2021-03-16 04:06 UTC
