### ISSUE TITLE
What is the future for separate MetaData when using multiple database bindings?

### ISSUE THREAD

**Issue by 4lph4-Ph4un** [pallets/flask-sqlalchemy#772] opened 2019-08-21 13:37 UTC
There was some planning/discussion about the subject some time ago. What's the status? Will it become possible to use same table names across different bindings?

**Comment by davidism** [comment] 2019-08-21 14:04
Duplicate of #222

**Closed by davidism** 2019-08-21 14:04 UTC

**Comment by 4lph4-Ph4un** [comment] 2019-08-21 14:07
When is this coming out? The discussion in the said issue has been prevented and no info on merging has been given? The last comments are from the end of last year.

**Comment by davidism** [comment] 2019-08-21 14:27
If and when it's merged, it will be available with the next release containing that merge. We do not have timelines for that.
