### ISSUE TITLE
Document differences between Flask-SQLAlchemy and SQLAlchemy

### ISSUE THREAD

**Issue by cal97g** [pallets/flask-sqlalchemy#795] opened 2019-12-09 20:30 UTC
It would be very useful to have a quick reference to exactly what Flask-SQLAlchemy is abstracting away or ways in which default SQLAlchemy behaviour has been altered.

The reason for this is due to the (well deserved) popularity of this library the majority of SQLAlchemy content refers directly to this version and may not be applicable to "vanilla" SQLAlchemy.

**Comment by davidism** [comment] 2019-12-09 21:16
Duplicate of #163

**Closed by davidism** 2019-12-09 21:16 UTC
