### ISSUE TITLE
convert_unicode deprecation warning with SQLAlchemy 1.3

### ISSUE THREAD

**Issue by zgoda** [pallets/flask-sqlalchemy#681] opened 2019-03-07 00:37 UTC
> _venv/lib/python3.7/site-packages/sqlalchemy/dialects/sqlite/base.py:1433: SADeprecationWarning: The create_engine.convert_unicode parameter and corresponding dialect-level parameters are deprecated, and will be removed in a future release.  Modern DBAPIs support Python Unicode natively and this parameter is unnecessary.
>     default.DefaultDialect.__init__(self, **kwargs)
> 

I guess this comes from `get_engine()` (https://github.com/pallets/flask-sqlalchemy/blob/master/flask_sqlalchemy/__init__.py#L558).

**Comment by zgoda** [comment] 2019-03-07 08:51
More on the context https://github.com/zzzeek/sqlalchemy/commit/4c2c2c40fde17c85013e00a6f3303a99e2b32c12#diff-d84f03db831ca7bb23f4dd0ea1ef3e6d

**Comment by davidism** [comment] 2019-03-07 13:06
Duplicate of #671

**Closed by davidism** 2019-03-07 13:06 UTC

**Comment by zgoda** [comment] 2019-03-07 13:43
Lol.
