### ISSUE TITLE
SQLALCHEMY_ECHO logger handler error

### ISSUE THREAD

**Issue by revmischa** [pallets/flask-sqlalchemy#724] opened 2019-05-06 13:14 UTC
If I set `SQLALCHEMY_ECHO=1` I get:
```
  File "/Users/cyber/dev/jb/bleh/api/monitor.py", line 25, in get
    return {'ok': bool(db.engine.execute("SELECT 1").scalar())}
  File "/Users/cyber/.virtualenvs/bleh-kgiLTi-5/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 937, in engine
    return self.get_engine()
  File "/Users/cyber/.virtualenvs/bleh-kgiLTi-5/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 956, in get_engine
    return connector.get_engine()
  File "/Users/cyber/.virtualenvs/bleh-kgiLTi-5/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 561, in get_engine
    self._engine = rv = self._sa.create_engine(sa_url, options)
  File "/Users/cyber/.virtualenvs/bleh-kgiLTi-5/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 966, in create_engine
    return sqlalchemy.create_engine(sa_url, **engine_opts)
  File "/Users/cyber/.virtualenvs/bleh-kgiLTi-5/lib/python3.7/site-packages/sqlalchemy/engine/__init__.py", line 435, in create_engine
    return strategy.create(*args, **kwargs)
  File "/Users/cyber/.virtualenvs/bleh-kgiLTi-5/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 177, in create
    engine = engineclass(pool, dialect, u, **engine_args)
  File "/Users/cyber/.virtualenvs/bleh-kgiLTi-5/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1864, in __init__
    self.echo = echo
  File "/Users/cyber/.virtualenvs/bleh-kgiLTi-5/lib/python3.7/site-packages/sqlalchemy/log.py", line 222, in __set__
    instance_logger(instance, echoflag=value)
  File "/Users/cyber/.virtualenvs/bleh-kgiLTi-5/lib/python3.7/site-packages/sqlalchemy/log.py", line 199, in instance_logger
    logger = InstanceLogger(echoflag, name)
  File "/Users/cyber/.virtualenvs/bleh-kgiLTi-5/lib/python3.7/site-packages/sqlalchemy/log.py", line 96, in __init__
    if self._echo_map[echo] <= logging.INFO and not self.logger.handlers:
KeyError: '1'
```

**Comment by lbeaufort** [comment] 2019-05-06 18:04
Hi, I'd like to work on this issue. I'll put in a PR to update `_echo_map` per @davidism

**Comment by rsyring** [comment] 2019-05-06 18:09
`_echo_map` is in SQLAlchemy.  I believe this issue is user error.  `1` is not a valid value.  It should be `True` or `False`.

IMO, we should update our docs to clarify and/or put a check in on our side to make sure it's `True` or `False`.

**Comment by lbeaufort** [comment] 2019-05-06 18:23
Whoops, just got there myself. Would it be more user friendly to have some error handling?

**Comment by rsyring** [comment] 2019-05-06 18:25
Actually, in this case, I think I'd just update the docs to say that this value simply gets passed through to `create_engine`'s `echo` param.  So whatever SA supports is what we support, but that `True` & `False` are recommended.

**Comment by rsyring** [comment] 2019-05-06 18:26
The other option is to submit an SQLAlchemy patch giving a better error message that explains what types/values are allowed for the echo value.

**Comment by rsyring** [comment] 2019-05-06 18:30
I added an issue in SA to give a better error message: https://github.com/sqlalchemy/sqlalchemy/issues/4665

If Mike (or someone) ends up picking up that issue, I think it will be sufficient to just update the docs on our side.

**Comment by rsyring** [comment] 2019-05-06 18:46
@lbeaufort based on Mike's response to our issue, it would be helpful if you or @revmischa could produce a https://stackoverflow.com/help/mcve so we can figure out if this is an FSA or SA problem.

**Comment by lbeaufort** [comment] 2019-05-06 19:25
Thanks @rsyring  - I'm unable to reproduce the issue with the following code - maybe I'm missing something.

Ran with:
```
export FLASK_APP=hello.py
flask run
```
Saved in `hello.py`:
```
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__)
app.config["SQLALCHEMY_ECHO"] = 1
#app.config["SQLALCHEMY_ECHO"] = '1' # I tried this too
app.config["SQLALCHEMY_DATABASE_URI"] = "sqlite:///example.sqlite"

db = SQLAlchemy(app)


@app.route('/')
def hello_world():
    return 'Hello, World!'


class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String, nullable=False)
    email = db.Column(db.String, nullable=False)


db.drop_all()
db.create_all()
db.session.add(User(username="Flask", email="example@example.com"))
db.session.commit()

users = User.query.all()

db.engine.execute("SELECT 1").scalar()

```

**Comment by rsyring** [comment] 2019-05-06 22:33
Since @lbeaufort was not able to reproduce, I'm going to close this issue.  @revmischa if you can provide a MCVE that reproduces, we'd be happy to re-open this issue.

Thanks.

**Closed by rsyring** 2019-05-06 22:33 UTC
