### ISSUE TITLE
flask-sqlalchemy 2.4 breaks create_engine code written before version 2.4

### ISSUE THREAD

**Issue by shalikashvili** [pallets/flask-sqlalchemy#763] opened 2019-07-11 18:21 UTC
The create_engine method _requires_ the engine_opts parameter, thus causing pre 2.4 code to throw TypeError exception. The engine_opts parameter should be optional

**Comment by davidism** [comment] 2020-05-26 22:11
Duplicate of #739.

**Closed by davidism** 2020-05-26 22:11 UTC
