### ISSUE TITLE
“A Minimal Application” of flask-sqlalchemy Official website can not run successfully when using the latest version(2.4.4) 

### ISSUE THREAD

**Issue by cuuxiao** [pallets/flask-sqlalchemy#932] opened 2021-03-18 06:00 UTC
**Description**
1. Install the latest flask-sqlalchemy(2.4.4) from [Official website](https://pypi.org/project/Flask-SQLAlchemy/#description);
2. It will install related packages, such as SQLAlchemy(1.4.0)
2. Refer to [A Minimal Application ](https://flask-sqlalchemy.palletsprojects.com/en/2.x/quickstart/#a-minimal-application)to complete my first demo program.
3. But unable to create database when running 'from app import db' and 'db.create_all()' in **flask shell**,The error is as follows:
![image](https://user-images.githubusercontent.com/31612669/111579356-d75c8e00-87f0-11eb-9056-d6225aaeb870.png)
4. The 'db.create_all()' can be run successfully and the database can be created successfully when I downgrade SQLAlchemy's version to 1.3.6

**Actual results**
The 'db.create_all()' can not be run successfully when the SQLAlchemy's version is 1.4.0 and 1.4.1

**Expected results** 
The 'db.create_all()' should be run successfully when the SQLAlchemy's version is 1.4.0 and 1.4.1, like 1.3.6. The flask-sqlalchemy
should be compatible with the latest SQLAlchemy

**Environment:** win

- Python version:3.7.9 
- Flask-SQLAlchemy version:2.4.4
- SQLAlchemy version:1.4.0

**Comment by cuuxiao** [comment] 2021-03-18 06:05
pls check and confirm, thanks a lot

**Comment by davidism** [comment] 2021-03-18 13:26
Duplicate of #927

**Closed by davidism** 2021-03-18 13:26 UTC
