### ISSUE TITLE
2.4.0 has been released without 2.3.3 changes

### ISSUE THREAD

**Issue by hanc1208** [pallets/flask-sqlalchemy#778] opened 2019-08-28 05:20 UTC
I couldn't find any commits of https://github.com/pallets/flask-sqlalchemy/pull/651 in 2.4.0.

**Comment by jinnovation** [comment] 2019-09-12 02:37
I can confirm this. Case in point, [`flask_sqlalchemy/model.py#123`](https://github.com/pallets/flask-sqlalchemy/blob/2c7fde1e11d6b6260230a4164cf4578786136606/flask_sqlalchemy/model.py#L123) does not reflect the change introduce in #651 and continues to read as follows:

        if bind_key is not None and hasattr(cls, '__table__'):

@davidism: Is there any plan to address this?

**Comment by kwlzn** [comment] 2019-09-24 07:49
same here. any updates?

**Comment by davidism** [comment] 2019-09-24 14:14
The PR you're pointing at was merged into master, not 2.x. There is no 2.3.3 release, it looks like that was an artifact of a merge while we were bumping to 2.4 instead. I can backport that PR as 2.4.1.

**Comment by davidism** [comment] 2019-09-24 14:36
https://pypi.org/project/Flask-SQLAlchemy/

**Closed by davidism** 2019-09-24 14:36 UTC

**Comment by kwlzn** [comment] 2019-09-25 07:17
@davidism thanks a ton!
