### ISSUE TITLE
Sessions not reconnecting cleanly on lost MySQL connection

### ISSUE THREAD

**Issue by spiritualized** [pallets/flask-sqlalchemy#626] opened 2018-06-07 20:54 UTC
When my MySQL server is restarted while a Flask app using flask-sqlalchemy is running (or the connection to the DB is lost for any reason), subsequent queries fail with
`sqlalchemy.exc.StatementError: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back`

It seems that upon a reconnection, the session should be tidied up by flask-sqlalchemy. Is this a correct assumption?

Specifics for reproduction:

```
app.config['SQLALCHEMY_DATABASE_URI'] = "mysql+pymysql://username:password@host:database"
db = SQLAlchemy(app)
```

isolation_level is READ_UNCOMMITTED
I have tried catching the exception and calling `db.session.rollback()` without success.

**Comment by fuhrysteve** [comment] 2018-06-19 17:01
By chance does this bug only occur when `sqlalchemy>=1.2.8`?

Having similar issues using postgresql and the latest version of sqlalchemy.. curious if it's related to this change: https://docs.sqlalchemy.org/en/latest/changelog/changelog_12.html#change-1.2.8-engine

**Comment by weibingo** [comment] 2018-06-20 03:06
i also find this issue.  and mysql first connection will take 'rollback' command to mysql server.

**Comment by alanhamlett** [comment] 2018-06-20 04:31
> subsequent queries fail

Are these queries in the same request or a new request?

Do queries in new requests also fail?

**Comment by spiritualized** [comment] 2018-06-20 04:35
Queries in new subsequent requests also fail.

**Comment by weibingo** [comment] 2018-06-21 01:37
@spiritualized you should add  finally: do.session.close()
to return connection to pool in any query or update.  
because if not , connection can along stay.

**Comment by rsyring** [comment] 2019-03-08 16:43
I don't use mysql, but we have issues like this happen when we patch our DB servers and they get restarted.  The problem is that SQLAlchemy uses connection pools and the connections it has open have been closed.  But SA won't detect this by default until you actually try to do something.  

SA added a feature for better handling of this in 1.2:

https://docs.sqlalchemy.org/en/latest/core/pooling.html#disconnect-handling-pessimistic

It's not really Flask-SQLAlchemy's job to handle this (so going to close this issue).  But, you should keep an eye on https://github.com/pallets/flask-sqlalchemy/issues/166 which is what you are waiting on to be able to easily use `pool_pre_ping` with Flask-SQLAlchemy.

**Closed by rsyring** 2019-03-08 16:43 UTC
Labels: config
