### ISSUE TITLE
make it possible to pass additional options to create_engine

### ISSUE THREAD

**Issue by gromgull** [pallets/flask-sqlalchemy#166] opened 2013-11-05 15:42 UTC
I needed to pass in an `isolation_level` parameters to the `create_engine` call. I did it like this: 

https://github.com/gromgull/flask-sqlalchemy/commit/689c90c48949dc4c020f16550576c517d2fb5230

(on top of the 1.0 tag since that's what we used, but I can make a pull-request with it applied to HEAD if you want)

**Comment by jayzeng** [comment] 2015-05-05 17:19
@immunda any update on this? we need to pass in a custom json json_serializer and need a way to specify/override engine_options, https://github.com/mitsuhiko/flask-sqlalchemy/pull/67/files looks good to me, any reason not to use that patch?

**Comment by immunda** [comment] 2015-05-05 17:25
This isn't going to be in the release 2.1 (very soon). However, it should definitely be addressed in v3.

@jayzeng It's not a problem with that commit per se, but there's a lot of details to sort out around documentation changes, tests and then managing the deprecation of options which such a solution would essentially override/render redundant.

**Comment by jayzeng** [comment] 2015-05-05 17:32
Completely understood. It is a pressing issue for us and I think we will just go for the subclass route. 

@immunda any rough estimate when v3 will be released?

**Comment by jayzeng** [comment] 2015-05-05 17:33
Also let me know what I can help to get it released asap

**Comment by rknLA** [comment] 2015-09-14 21:37
I'm also interested in some way to do this.  I need to [pass a custom connection function](http://docs.sqlalchemy.org/en/latest/core/pooling.html#using-a-custom-connection-function), and right now have to do some monkey patching around to get there.

Is there any value in working on or submitting a proposed fix at this point?

**Comment by antoine-lizee** [comment] 2016-09-15 15:16
+1 here too, in order to pass a custom `json_serializer`.

**Comment by rsyring** [comment] 2017-02-21 16:34
This really needs to be fixed.  It could be easily done by accepting a `SQLALCHEMY_ENGINE_OPTS` config value that is a dict and that would be merged into the options before being sent to create_engine().  That seems preferable to the implementation in #431 IMO.

This could literally be a two line change:

```python
            options = {'convert_unicode': True}
            self._sa.apply_pool_defaults(self._app, options)
            self._sa.apply_driver_hacks(self._app, info, options)
            if echo:
                options['echo'] = echo

            # next two lines are new
            config_engine_opts = self._app.config.get('SQLALCHEMY_ENGINE_OPTS', {})
            options.update(config_engine_opts)

            self._engine = rv = sqlalchemy.create_engine(info, **options)
```

Or, go slightly more customizable, and put those two lines in a new method `SQLAlchemy.apply_engine_defaults()` so that it can be easily overridden.

@davidism or @immunda would you accept a PR with this approach?

**Comment by PeterParker** [comment] 2017-06-23 15:30
@davidism @immunda - Bump.

A response would be great re: whether or not a PR with @rsyring's approach would be accepted.

My particular use-case has to do with [disconnect handling](http://docs.sqlalchemy.org/en/latest/core/pooling.html#disconnect-handling-pessimistic).

**Comment by davidism** [comment] 2017-06-23 15:35
There's already a PR open: #487. We will get to it when we have time available. No need to ping us, we're still aware of open issues.

**Comment by rsyring** [comment] 2017-08-04 18:29
FWIW, SQLAlchemy 1.2 is coming out with a new method of detecting connections in the pool that are no longer valid: 

https://docs.sqlalchemy.org/en/latest/core/pooling.html#pool-disconnects-pessimistic

We really want to use that and without this issue getting resolved, it is going to be much harder to do so.

This can be a two line change, as demonstrated above.  I'll write the PR, I just want someone to tell me before I make the effort that my approach will work.

**Comment by dolfandringa** [comment] 2017-09-21 03:49
I second this. I need it for using sqlite in memory databases with unittesting, i.e.: http://www.sameratiani.com/2013/09/17/flask-unittests-with-in-memory-sqlite.html

**Comment by austinmcconnell** [comment] 2017-11-30 21:51
I'll third this. This functionality would be super useful.

**Comment by davidism** [comment] 2017-11-30 22:00
Please use the reaction buttons to vote on issues.

**Comment by rsyring** [comment] 2018-05-29 20:31
If anyone working on this project is a consultant, I'd be happy to hire you to get this issue resolved.  Please contact me directly regarding.  Thanks.

**Comment by georgeslabreche** [comment] 2018-06-25 21:49
I would like to see @rsyring's solution implemented. In the meantime, we've opted to move forward with the following approach: https://github.com/mitsuhiko/flask-sqlalchemy/issues/589#issuecomment-361075700

The subclassing approach is the same solution that @gilbsgilbs has referred to when closing the following related Issue: https://github.com/mitsuhiko/flask-sqlalchemy/pull/577

**Comment by gdoron** [comment] 2018-07-13 10:56
You cannot love enough open source.
Adding two lines of code high demand issue sits idle for several years.
And the only comment made by the author is: "We will get to it when we have time available".
If you don't have the available time, maybe it's time to pass the torch to someone else.

(Appreciate the initial contribution, **really!** but this is just painful to watch)

**Comment by davidhalter** [comment] 2018-07-13 11:33
@gdoron The problem is not that people don't want to pass the torch. The problem is that there are not enough people available for maintenance.

As an Open Source maintainer myself (not on this one), I can assure you that there are almost no people consistently contributing to projects over years. Most people do one or two pull requests and then leave. Adding additional maintainers is therefore not a question of giving up responsibility, but rather finding the right people.

The only person that actually tried to solve something here was @rsyring, because he offered to pay something.

If you actually cared about this project enough, you would either solve this problem with a new competing project that cleans up a lot of the issues that are part of this one or start to work with the issue tracker/pull requests of this one and lend a helping hand until you become a maintainer yourself. That is how it works and how everyone benefits from Open Source. You are also a part of this world and you can help to improve it :)

**Comment by gdoron** [comment] 2018-07-13 11:51
@davidhalter

> If you actually cared about this project enough, you would either solve this problem with a new competing project that cleans up a lot of the issues that are part of this one or start to work with the issue tracker/pull requests of this one and lend a helping hand until you become a maintainer yourself.

There are already too many PRs opened, creating new ones won't help.
I think finding other maintainers to join is harder when you let their issues and Pull-Requests sit idle for years.

I don't actually care enough about this project, I'm only using it in a private project to learn Flask.
I know I don't have the right to complain, but as I wrote, it's just painful to watch.

**Comment by rsyring** [comment] 2019-03-07 21:58
Per (https://github.com/pallets/flask-sqlalchemy/pull/540#issuecomment-470643872), I'll be opening a PR shortly (unless someone beats me to it) that:

* Let's you configure the engine from config options: `SQLALCHEMY_ENGINE_OPTIONS`
* Lets you configure the engine from `engine_options` in: https://github.com/pallets/flask-sqlalchemy/blob/500e732dd1b975a56ab06a46bd1a20a21e682262/flask_sqlalchemy/__init__.py#L675

After some additional though, I'm also think it would make sense to Adjust `_EngineConnector` https://github.com/pallets/flask-sqlalchemy/blob/500e732dd1b975a56ab06a46bd1a20a21e682262/flask_sqlalchemy/__init__.py#L532 to have a `def get_options()` and `def create_engine()` so that if the options above are insufficient for some reason, it's relatively easy to create the engine however you want it created.  In this case, I also think we should drop `_` from EngineConnector so signal it's ok to inherit and customize.  It make sense to me to do it this way, but I guess we can see if that flies during the PR review.

**Closed** 2019-04-18 00:27 UTC
Labels: config
