### ISSUE TITLE
drop_all() not cascading

### ISSUE THREAD

**Issue by revmischa** [pallets/flask-sqlalchemy#722] opened 2019-05-03 07:48 UTC
I am trying to use:
```
db.drop_all(app=app)
db.create_all(app=app)
```
to recreate my schema while I am still in early development.

It appears to be dropping tables in the wrong order.

```
  File "/var/task/flask_sqlalchemy/__init__.py", line 971, in drop_all
    self._execute_for_all_tables(app, bind, 'drop_all')
  File "/var/task/flask_sqlalchemy/__init__.py", line 955, in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), **extra)
  File "/var/task/sqlalchemy/sql/schema.py", line 4313, in drop_all
    ddl.SchemaDropper, self, checkfirst=checkfirst, tables=tables
  File "/var/task/sqlalchemy/engine/base.py", line 2033, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/var/task/sqlalchemy/engine/base.py", line 1607, in _run_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/var/task/sqlalchemy/sql/visitors.py", line 131, in traverse_single
    return meth(obj, **kw)
  File "/var/task/sqlalchemy/sql/ddl.py", line 949, in visit_metadata
    table, drop_ok=True, _is_metadata_operation=True
  File "/var/task/sqlalchemy/sql/visitors.py", line 131, in traverse_single
    return meth(obj, **kw)
  File "/var/task/sqlalchemy/sql/ddl.py", line 1002, in visit_table
    self.connection.execute(DropTable(table))
  File "/var/task/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/var/task/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/var/task/sqlalchemy/engine/base.py", line 1050, in _execute_ddl
    compiled,
  File "/var/task/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "/var/task/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/var/task/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/var/task/sqlalchemy/util/compat.py", line 128, in reraise
    raise value.with_traceback(tb)
  File "/var/task/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/var/task/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.InternalError: (psycopg2.InternalError) cannot drop table video because other objects depend on it                                                                                          
DETAIL:  constraint user_video_rating_video_id_fkey on table user_video_rating depends on table video
HINT:  Use DROP ... CASCADE to drop the dependent objects too.

[SQL: DROP TABLE video]
```

Perhaps adding `cascade` in `drop_all()` would help?

**Comment by rsyring** [comment] 2019-05-06 22:29
I don't think this is likely to be a bug in Flask-SQLAlchemy.  If you disagree and can produce a https://stackoverflow.com/help/mcve that demonstrates this is a bug in FSA, then I'd be happy to re-open this issue.

**Comment by jetbridge-services** [comment] 2019-05-09 08:03
What do you think it is a bug in then?

I don't know the magical combination of tables and relationships needed to recreate this bug. But clearly it exists, based on the stack trace.

**Comment by lbeaufort** [comment] 2019-05-09 17:19
It seems feasible to add an optional cascade parameter, or change the default in version 3. I could work on reproducing this if it’s helpful.

**Comment by rsyring** [comment] 2019-05-09 17:45
I guess it could be a feature addition if someone wanted to tackle it.  SQLAlchemy has the meta data already sorted and even a `drop_all()` method.  Some details are here:

https://stackoverflow.com/questions/11233128/how-to-clean-the-database-dropping-all-records-using-sqlalchemy

With SA having the tools to do it, I wonder why we are rolling our own here.  For 3.0, maybe we should get rid of `db.drop_all()` and point people to `db.metadata.drop_all()` which should point to SQLAlchemy's version.

**Comment by bryan5989** [comment] 2020-10-08 16:10
This is how I work around it:

```python
def drop_everything():
    """(On a live db) drops all foreign key constraints before dropping all tables.
    Workaround for SQLAlchemy not doing DROP ## CASCADE for drop_all()
    (https://github.com/pallets/flask-sqlalchemy/issues/722)
    """
    from sqlalchemy.engine.reflection import Inspector
    from sqlalchemy.schema import DropConstraint, DropTable, MetaData, Table

    con = db.engine.connect()
    trans = con.begin()
    inspector = Inspector.from_engine(db.engine)

    # We need to re-create a minimal metadata with only the required things to
    # successfully emit drop constraints and tables commands for postgres (based
    # on the actual schema of the running instance)
    meta = MetaData()
    tables = []
    all_fkeys = []

    for table_name in inspector.get_table_names():
        fkeys = []

        for fkey in inspector.get_foreign_keys(table_name):
            if not fkey["name"]:
                continue

            fkeys.append(db.ForeignKeyConstraint((), (), name=fkey["name"]))

        tables.append(Table(table_name, meta, *fkeys))
        all_fkeys.extend(fkeys)

    for fkey in all_fkeys:
        con.execute(DropConstraint(fkey))

    for table in tables:
        con.execute(DropTable(table))

    trans.commit()
```

Note: db here is an instance of SQLAlchemy() from flask_sqlalchemy
You could make it vanilla sqlalchemy too:

```python
def drop_everything(engine: Engine):
    """(On a live db) drops all foreign key constraints before dropping all tables.
    Workaround for SQLAlchemy not doing DROP ## CASCADE for drop_all()
    (https://github.com/pallets/flask-sqlalchemy/issues/722)
    """
    from sqlalchemy.engine.reflection import Inspector
    from sqlalchemy.schema import (
        DropConstraint,
        DropTable,
        MetaData,
        Table,
        ForeignKeyConstraint,
    )

    con = engine.connect()
    trans = con.begin()
    inspector = Inspector.from_engine(db.engine)

    # We need to re-create a minimal metadata with only the required things to
    # successfully emit drop constraints and tables commands for postgres (based
    # on the actual schema of the running instance)
    meta = MetaData()
    tables = []
    all_fkeys = []

    for table_name in inspector.get_table_names():
        fkeys = []

        for fkey in inspector.get_foreign_keys(table_name):
            if not fkey["name"]:
                continue

            fkeys.append(ForeignKeyConstraint((), (), name=fkey["name"]))

        tables.append(Table(table_name, meta, *fkeys))
        all_fkeys.extend(fkeys)

    for fkey in all_fkeys:
        con.execute(DropConstraint(fkey))

    for table in tables:
        con.execute(DropTable(table))

    trans.commit()
```

**Comment by davidism** [comment] 2021-03-22 17:42
Due to the way Flask-SQLAlchemy evolved support for multiple binds, we are using `Model.metadata.tables.values()` to get a list of tables to drop for a given bind, which probably messes with SQLAlchemy's `drop_tables` implementation. We should be using SQLAlchemy 1.0's `sort_tables_and_constraints` if we want to keep doing this manually.

However, this all stems from the fact that we don't use a separate metadata per bind. Solving #222 should solve this issue as well.

**Comment by davidism** [comment] 2021-03-22 18:03
We've tried to reproduce this issue but couldn't come up with an example. Based on my previous comment, I think if this is an issue it's better solved by unique metadata per bind anyway. Closing this.

**Closed by davidism** 2021-03-22 18:03 UTC

**Comment by SheepReaper** [comment] 2021-03-22 18:41
Reproducing the issue is complicated... The problem pops for me specifically with postgresql and when the schema is large and with many relationships (and mix of all types and complexity). Not to mention that enumeration types for postgres are ignored. I can't paste the schema here or give a repo for reasons...

drop_all() is essentially useless for postgres for all except trivially simple schemas.

1. Should this be a bug against sqlalchemy instead?
2. Unique Metadata likely has nothing to do with this problem.
3. drop_all() just needs to do a better job determining the order in which to drop tables OR forget the order, drop constraints, and then drop tables.

**Comment by ThiefMaster** [comment] 2021-03-22 18:43
3: ...OR add `CASCADE` to the DROP TABLE ;)

**Comment by SheepReaper** [comment] 2021-03-22 18:44
^^^ what he said

**Comment by davidism** [comment] 2021-03-22 18:46
This is related to how we're handling binds and metadata. If we weren't getting a list of tables ourselves, we'd just be calling `metadata.drop_all` without passing a list, and SQLAlchemy should do the right thing. If it doesn't, then that's a bug with SQLAlchemy. Regardless, I don't plan to make changes to our `drop_table` except in relation to #222.
