### ISSUE TITLE
_bind_key not working for views

### ISSUE THREAD

**Issue by satyamprasad** [pallets/flask-sqlalchemy#891] opened 2020-12-04 07:47 UTC
I am using PostgreSQL as my backend database.I am using two databases URLs for my project

```python
try:
    create_all(bind='URL1')
    create_all(bind='URL2')
except exc.OperationalError as e:
    err = "Error occurred while creating schemas in database: {}".format(str(e))
    print(err)
    sys.exit(1)
```

My problem is if i specify _bind_key for tables, it works absolutely fine and creates the table in the specific DB only. But for views it tries to create in both databases even after specifying bind key.

db_model.py

```python
class User(db.Model):
    __bind_key__   = 'URL1'
    __tablename__ = 'table1'
    __table_args__ = {'extend_existing': True}

    id             = db.Column(db.Integer, primary_key=True)
    username       = db.Column(db.String(32), unique=True, nullable=False)

    def __init__(self, username = None):
        self.username = username

    def __repr__(self):
       return '<Username %r>' % self.username
```

view_model.py

```python
@compiles(CreateView)
def compile_create_materialized_view(element, compiler, **kw):
    return 'DROP {}VIEW IF EXISTS {};CREATE {}VIEW {} AS {}'.format(
    'MATERIALIZED ' if element.materialized else '',
    element.name,
    'MATERIALIZED ' if element.materialized else '',
    element.name,
    compiler.sql_compiler.process(element.selectable, literal_binds=True),
)

class UserView(db.Model):
 __bind_key__   = 'URL1'
 __tablename__ = 'my_view'
 __table__ = sqlalchemy_utils.create_view(__tablename__, sqlalchemy.select([User]), db.Model.metadata)
```

init.py

```python
from .db_model import User
from .db_view import UserView
```

I get this error

```
db_mgr_1  |     cursor.execute(statement, parameters)
db_mgr_1  | sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "table1" does not exist
db_mgr_1  | LINE 2: FROM table1
db_mgr_1  |              ^
db_mgr_1  |
db_mgr_1  | [SQL: DROP VIEW IF EXISTS my_view;CREATE VIEW my_view AS SELECT table1.id, table1.username
db_mgr_1  | FROM table1]
```

The view gets created in the URL1 database but fails in URL2 database as underlying table is created only in URL1 database. Can somebody please let me know how i can specify view to bind to a specific database in SQLAlchemy.

**Comment by davidism** [comment] 2021-03-24 19:26
Duplicate of #125

**Closed by davidism** 2021-03-24 19:26 UTC

**Comment by davidism** [comment] 2021-03-24 19:39
Duplicate of #834 and #125
